uint8 requested_mode
uint8 MODE_IDLE=0
uint8 MODE_MANUAL=1
uint8 MODE_AUTONOMOUS=2
uint8 MODE_ESTOP=3
uint8 MODE_TARGETING_LOCK=4
---
bool success
string message
uint8 previous_mode
uint8 current_mode
